version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - APP_PORT=8080
      - CACHE_CLEANUP_INTERVAL_TIME=10
      - CACHE_DEFAULT_EXPIRATION_TIME=10
      - LOG_FILE=logfile
      - LOG_LEVEL=INFO
      - JAEGER_URL=jaeger:14268
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one:1.9
    ports:
      - '16686:16686'
      - '14268:14268'
      - '6831:6831/udp'