version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '2222:2222'
    environment:
      - APP_PORT=8080
      - CACHE_CLEANUP_INTERVAL_TIME=10
      - CACHE_DEFAULT_EXPIRATION_TIME=10
      - LOG_FILE=logfile
      - LOG_LEVEL=INFO
      - JAEGER_URL=jaeger:14268
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one:1.9
    ports:
      - '16686:16686'
      - '14268:14268'
      - '6831:6831/udp'

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=:9099'
    ports:
      - '9099:9099'
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus_data:
    driver: local