name: DockerHub Build and Push

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: "${{ secrets.DOCKER_HUB }}/docker-client"
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          dockerfile: Dockerfile
